## Bag Of Words 

#### Using CountVectorizer()

In [23]:
import numpy as np 
import pandas as pd 
#creating Data Frame
df=pd.DataFrame({'Text':['Rabindra is Coding','Rabindra uses Python for coding','Hello Angel'],'Output':[1,1,0]})
df

Text  Output
0               Rabindra is Coding       1
1  Rabindra uses Python for coding       1
2                      Hello Angel       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True)

In [4]:
bow=cv.fit_transform(df['Text'])

In [5]:
print(cv.vocabulary_) #shows index

{'rabrindra': 7, 'is': 4, 'coding': 1, 'rabindra': 6, 'uses': 8, 'python': 5, 'for': 2, 'hello': 3, 'angel': 0}


In [6]:
print(bow[0].toarray())
print(bow[2].toarray())

[[0 1 0 0 1 0 0 1 0]]
[[1 0 0 1 0 0 0 0 0]]


In [7]:
cv.transform(['Rabindra is coding chess']).toarray()  #out of vocabulary problem is getting Handeled "new word is chess"

array([[0, 1, 0, 0, 1, 0, 1, 0, 0]], dtype=int64)

## NGrams

In [8]:
df1=pd.DataFrame({'Text':['Rabrindra is Coding','Rabindra uses Python for coding','Hello Angel'],'Output':[1,1,0]})
df1

Text  Output
0              Rabrindra is Coding       1
1  Rabindra uses Python for coding       1
2                      Hello Angel       0

In [13]:
cv1=CountVectorizer(ngram_range=(3,3))

In [14]:
bow1=cv1.fit_transform(df1['Text'])

In [15]:
print(cv1.vocabulary_)

{'rabrindra is coding': 2, 'rabindra uses python': 1, 'uses python for': 3, 'python for coding': 0}


In [16]:
print(bow1[0].toarray())
print(bow1[1].toarray())
print(bow1[2].toarray())

[[0 0 1 0]]
[[1 1 0 1]]
[[0 0 0 0]]


##### Len of your vocabulary

In [17]:
print(len(cv.vocabulary_))

9


## TF-IDF

#### Unlike other techniques assigns different weights to vocabulary based on frequency

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
rabindra=tfidf.fit_transform(df['Text']).toarray()
rabindra

array([[0.        , 0.51785612, 0.        , 0.        , 0.68091856,
        0.        , 0.51785612, 0.        ],
       [0.        , 0.37302199, 0.49047908, 0.        , 0.        ,
        0.49047908, 0.37302199, 0.49047908],
       [0.70710678, 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.        ]])

In [25]:
print(tfidf.idf_) # Prints  Idf Value for different vocabularies 
print(tfidf.get_feature_names_out())

[1.69314718 1.28768207 1.69314718 1.69314718 1.69314718 1.69314718
 1.28768207 1.69314718]
['angel' 'coding' 'for' 'hello' 'is' 'python' 'rabindra' 'uses']
